runtime: python310  # Use your Python version

entrypoint: gunicorn -b :$PORT core.wsgi

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"
